### PR TITLE
Generated code for Pokemon API entites

### PR DESCRIPTION
**Pull request by zereddiamond**
pom.xml inspired by Fruits projects

### CODE REVIEW

**Review by Obyka — CHANGES_REQUESTED** [review]
There are multiple generated files with Fruit in their name ? Is that normal ? Where can we change it' ?

**Comment by zereddiamond** [comment]
Yes, I forget these files, I deleted them.

**Comment by zereddiamond** [comment]
> 
> 
> There are multiple generated files with Fruit in their name ? Is that normal ? Where can we change it' ?

Corrected it.

**Review by Obyka — APPROVED** [review]
Great job ! Seems clean

**Pull request merged**
